spring:
  r2dbc:
    url: "r2dbc:h2:mem://./r2dbc"
    username: "dbuser"
    password: "dbpass"
  datasource:
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    driver-class-name: org.h2.Driver
server:
  port: 7676
