spring:
  datasource:
    #  h2-database 文件模式 后面加上MODE=MYSQL;可以兼容mysql语法
    url: jdbc:h2:file:/data/demo;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MODE=MYSQL;;
    username: sa
    password: sa
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    driver-class-name: org.h2.Driver
    hikari:
      max-lifetime: 120000
      connection-test-query: select * from dual
    # 见 H2ConsoleAutoConfiguration
  h2:
    console:
      path: "/h2-console"
      enabled: true
    settings:
      webAllowOthers: true
server:
  port: 8181